The_Tutoria_Project/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from main import views
from django.contrib import admin
from django.conf import settings
from django.contrib.auth.views import (
   password_reset,
   password_reset_done,
   password_reset_confirm,
   password_reset_complete
)

from The_Tutoria_Project.admin import courseadmin


urlpatterns = [

    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^main/', include('main.urls')),
    url(r'^', include('django.contrib.auth.urls')),


    # url(r'^admin/', admin.site.urls),
    # url(r'^account/', include('django.contrib.auth.urls')),
    # the new password reset URLs
    # url(r'^accounts/password/reset/$',
    #     password_reset,
    #     {'template_name':
    #     'registration/password_reset_form.html'},
    #     name="password_reset"),
    # url(r'^accounts/password/reset/done/$',
    #     password_reset_done,
    #     {'template_name':
    #     'registration/password_reset_done.html'},
    #     name="password_reset_done"),
    # url(r'^accounts/password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
    #     password_reset_confirm,
    #     {'template_name':
    #     'registration/password_reset_confirm.html'},
    #     name="password_reset_confirm"),
    # url(r'^accounts/password/done/$',
    #     password_reset_complete,
    #     {'template_name':
    #     'registration/password_reset_complete.html'},
    #     name="password_reset_complete"),
    # url(r'^accounts/',
    #     include('registration.backends.simple.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^courseadmin/', courseadmin.urls),


    #url(r'^accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.conf.urls import url

from django.views.generic.detail import DetailView
from django.conf.urls.static import static
from main import views
from django.conf import settings
from django.conf.urls import include, url
# from main.admin import my_new_admin
from django.contrib import admin
from django.contrib.auth.views import (
   password_reset,
   password_reset_done,
   password_reset_confirm,
   password_reset_complete
)

app_name = 'main'

urlpatterns = [
    url(r'^$', views.IndexView.as_view()),
    url(r'^home/$', views.homePage, name='home-page'),
    url(r'^search/$', views.search, name='search'),
    url(r'^reset-password/$',password_reset, name = 'password_reset'),
    url(r'^reset-password/done/$',password_reset_done, name = 'password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',password_reset_confirm, name = 'password_reset_confirm'),
    url(r'^reset-password/complete/$',password_reset_complete, name = 'password_reset_complete'),
    url(r'^register/$', views.register, name='register'),
    url(r'^studentreg/$', views.studentRegistration, name='studentreg'),
    url(r'^tutorreg/$', views.register2, name='tutorreg'),
    url(r'^change_password/$', views.change_password, name='change_password'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^tutorWallet/$', views.tutorWallet, name='tutorWallet'),
    url(r'^studentWallet/$', views.studentWallet, name='studentWallet'),
    url(r'^myTutorsWallet/$', views.myTutorsWallet, name='myTutorsWallet'),
    url(r'^tutorSchedule/$', views.tutorSchedule, name='tutorSchedule'),
    url(r'^blockSuccess/$', views.blockSuccess, name='blockSuccess'),
    url(r'^user_login/$', views.user_login, name='user_login'),
    url(r'^tutor_login/$', views.user_login1, name='tutor_login'),
    url(r'^tutorhome/$', views.tutorHome, name='tutor_home'),
    url(r'^session/$', views.bookSession, name='session'),
    url(r'^confirmedBooking/$', views.confirmedBooking, name='confirmedBooking'),
    url(r'^mySessions/$', views.mySessions, name='mySessions'),
    url(r'^tutors$', views.TutorListView.as_view(), name='tutor-list'),
    url(r'^tutors/(?P<pk>\d+)$', views.TutorDetailView, name='tutor-detail'),
    url(r'^tutors/viewprofile/', views.TutorViewProfile, name='tutor-viewprofile'),
    url(r'^myTutors$', views.myTutorsHome, name='myTutors'),
    url(r'^tutors/update/(?P<pk>\d+)$', views.TutorUpdateView.as_view(), name='tutor-update'),
    url(r'^reviews$', views.review, name='review-list'),
    url(r'^reviews/(?P<pk>\d+)$', views.reviewForm, name='review-form'),
    url(r'^tutorMySessions$', views.tutorMySessions, name='tutorMySessions')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/forms.py
from django import forms
from django.contrib.auth.models import User
from main.models import Student, Sessions, Tutor


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'password', 'email')
        # remove email


class StudentInfoForm(forms.ModelForm):
    class Meta():
        model = Student
        fields = ('firstName', 'lastName', 'avatar', 'phoneNo')


class TutorInfoForm(forms.ModelForm):
    class Meta():
        model = Tutor
        fields = ('firstName', 'lastName', 'courses',
                  'university_name', 'hourly_rate', 'tutor_intro', 'isStudent','phoneNo', 'searchTags', 'avatar', 'tutorType')


class BookingForm(forms.ModelForm):
    class Meta():
        model = Sessions
        fields = ('tutorID', 'studentID', 'bookedDate', 'bookedStartTime', 'bookedEndTime')

main/views.py
import json

from . import models
from main.forms import UserForm, StudentInfoForm, BookingForm, TutorInfoForm

#Searching
from django.db.models import Q
from django.db.models import Max
from decimal import Decimal as D

from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, render_to_response, redirect
from django.shortcuts import get_object_or_404
from django.template import RequestContext
from django.views.generic import View, ListView, DetailView, TemplateView, UpdateView

from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from main.models import Availability, Sessions, Student, Tutor, Course, SystemWallet, Transactions, Review
from django.db import IntegrityError
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.contrib.sites.models import Site
from django.http import JsonResponse, Http404
from django.contrib.auth.models import Permission
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.forms import PasswordChangeForm
from datetime import datetime, timedelta
from django.contrib.auth import update_session_auth_hash
from django.contrib.admin.views.decorators import staff_member_required
from django.core.mail import send_mail

class IndexView(TemplateView):
    template_name = 'index.html'


def signup(request):
    return render(request, 'signup.html', {})


def change_password(request):

    if request.method == "POST":
        form = PasswordChangeForm(data = request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request,form.user)
            return redirect('/main/home')
        else:
            return redirect('/main/change_password')


    else:
        form = PasswordChangeForm(user=request.user)
        args = {'form': form}
        return render(request, 'main/change_password.html',args)

# Authorisation view using the built in Django authorisation model.
def register(request):
    registered = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        # Student_form=StudentInfoForm(data=request.POST)

        if user_form.is_valid():
            # and Student_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            registered = True

            login(request, user)

            print(user.username)
            render(request, 'main/registration.html',
                   {'user': user, 'registered': registered})

        else:
            print(user_form.errors)

    else:
        user_form = UserForm()

    return render(request, 'main/registration.html', {'user_form': user_form, 'registered': registered})


# Authorisation view using the built in Django authorisation model.
def studentRegistration(request):
    registered = False
    uid = request.GET['value1']
    print(request.user)

    if request.method == "POST":

        Student_form = StudentInfoForm(request.POST, request.FILES)

        if Student_form.is_valid():

            Student = Student_form.save(commit=False)

            Student.user = request.user
            Student.email = request.user.email
            # print(request.FILES)
            # if 'avatar' in request.FILES:
            #     Student.avatar = request.FILES['avatar']

            Student.save()

            registered = True

        else:
            print(Student_form.errors)

    else:
        # user_form=UserForm()
        Student_form = StudentInfoForm()

    return render(request, 'main/studentreg.html', {'Student_form': Student_form, 'registered': registered, 'user': request.user})


# Authorisation view using the built in Django authorisation model.
''' Tutor registration '''
def register2(request):
    registered = False
    uid = request.GET['value1']
    print(User.objects.get(username=uid))

    if request.method == "POST":

        Tutor_form = TutorInfoForm(request.POST, request.FILES)

        if Tutor_form.is_valid():

            tutorInst = Tutor_form.save(commit=False)
            tutorInst.user = request.user
            tutorInst.tutor_email = request.user.email

            print(request.FILES)

            # if len(request.FILES) == 0
            # print(request.FILES['avatar'])
            # if 'avatar' in request.FILES:
            #     Tutor.avatar = request.FILES['avatar']

            # if len(request.FILES) != 0:
            # myfile = request.FILES['myfile']
            # fs = FileSystemStorage()
            # avatar = fs.save(str(myfile),myfile)


            if (tutorInst.isStudent == True):
                Student_instance = Student.objects.create(
                    user=request.user, firstName=tutorInst.firstName, lastName=tutorInst.lastName, email=tutorInst.tutor_email, wallet=tutorInst.wallet, phoneNo=tutorInst.phoneNo, avatar=tutorInst.avatar)
                Student_instance.save()
            tutorInst.save()
            Tutor_form.save_m2m()
            registered = True

        else:
            print(Tutor_form.errors)

    else:
        # user_form=UserForm()
        Tutor_form = TutorInfoForm()

    return render(request, 'main/tutorreg.html', {'Tutor_form': Tutor_form, 'registered': registered})


def choose_login(request):
    return render(request, 'Chooselogin.html', {})


'''Student login '''
def user_login(request):


    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
        print(str(user))
        if user:
            if user.is_active:
                login(request, user)
                return redirect('/main/home/')
                # return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT INACTIVE")
        else:
            print("Login failed")
            return HttpResponse("Invalid login details")


    return render(request, 'main/login.html', {})


'''Tutor Login'''
def user_login1(request):  # For Tutor
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:

                try:
                    Tutor.objects.get(user=user)
                    login(request, user)
                    return redirect('/main/tutorhome/')
                    # return HttpResponseRedirect(reverse('index'))

                except:
                    return HttpResponse("Sorry! You are not registered as a Tutor!")

            else:
                return HttpResponse("ACCOUNT INACTIVE")
        else:
            print("Login failed")
            return HttpResponse("Invalid login details")
    else:
        return render(request, 'main/login1.html', {})

def tutorHome(request):
    return render(request, 'main/tutor_home.html', {})


def myTutorsHome(request):

    if request.method == 'POST':

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active and user.is_staff:
                return redirect('/main/myTutorsWallet/')

    return render(request, 'main/loginMyTutors.html', {})

@login_required
def myTutorsWallet(request):

    currentUser=request.user
    sysWallet = Site.objects.get_current().systemwallet

    if request.method == 'POST':

        amount = 0
        amountstr = request.POST.get("amount")

        try:
            amount = (float)(amountstr)
        except:
            amount = 0

        if (float)(sysWallet.systemBalance) > amount:
            sysWallet.systemBalance = (float)(sysWallet.systemBalance) - amount
            sysWallet.save()
            return render(request,'main/myTutorsWallet.html', {'user': request.user, 'wallet': sysWallet})


    return render(request, 'main/myTutorsWallet.html', {'user': request.user, 'wallet': sysWallet})


class TutorListView(ListView):

    context_object_name = 'tutors'
    model = models.Tutor

@login_required
def TutorDetailView(request, pk):

    tutor = get_object_or_404(Tutor, id=pk)
    review = Review.objects.filter(session__tutorID=tutor, submitted=True)
    reviewCount = Review.objects.filter(session__tutorID=tutor, submitted=True).count()
    print(review)
    return render(request, 'main/tutor_detail.html', {'tutor_details': tutor, 'reviews':review, 'reviewCount':reviewCount})

@login_required
def TutorViewProfile(request):

    try:
        tutor = Tutor.objects.get(user=request.user)
    except:
        return HttpResponse("Sorry! You are not registered as a Tutor!")

    review = Review.objects.filter(session__tutorID=tutor, submitted=True)
    # reviewCount = Review.objects.filter(session__tutorID=tutor, submitted=True).count()
    return render(request, 'main/tutor_viewprofile.html', {'tutor': tutor, 'reviews':review })

class TutorUpdateView(UpdateView):
    fields = ('tutor_email','avatar','phoneNo','university_name','courses','tutor_intro','hourly_rate','isActive','searchTags')
    model = models.Tutor


@login_required
''' View Available Sessions to book'''
def bookSession(request):

    current_user = request.user
    try:
        student = Student.objects.get(user=current_user)  # student
    except:
        return HttpResponse("Sorry! You are not registered as a Student!")

    tutorID = request.GET["value1"]
    tutor = Tutor.objects.get(id=tutorID)  # get tutor object

    slot = Availability.objects.filter(tutor_id=tutorID)  # blocked slots

    currentDate = str(datetime.today().date())

templates/main/Chooselogin.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <li><a href="{% url 'main:user_login' %}">LOGIN AS STUDENT</a></li>
    <li><a href="{% url 'main:tutor_login' %}">LOGIN AS TUTOR</a></li>

  </body>
</html>

templates/main/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">


        
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'main:register' %}">Register</a></li>
          {% if user.is_authenticated %}
          <li><a class='navbar-link' href="{% url 'logout' %}">Logout</a></li>
          {% else %}
           <li><a class="navbar-link" href="{% url 'main:user_login' %}">Login</a></li>
           {% endif %}




        </ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>


  </body>
</html>

templates/main/index.html
 {% extends "main/base.html" %}
 {% block body_block %}
 <div class="jumbotron">
   <h1>Admin Page</h1>
 </div>

 {% endblock %}

templates/main/login.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">

  <meta charset="utf-8">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/materialdesignicons.min.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/prettyPhoto.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/unslider.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/template.css' %}" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<title> Tutoria </title>

</head>

<body data-target="#nino-navbar" data-spy="scroll">

	<!-- Header
    ================================================== -->
	<header id="nino-header">
		<div id="nino-headerInner">
			<nav id="nino-navbar" class="navbar navbar-default" role="navigation">
				<div class="container">

					<!-- Brand and toggle get grouped for better mobile display -->
					<div class="navbar-header">
						<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nino-navbar-collapse">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<a class="navbar-brand" href="{% url 'index' %}">Tutoria</a>
					</div>

					<!-- Collect the nav links, forms, and other content for toggling -->


					<div class="nino-menuItem pull-right">
						<div class="collapse navbar-collapse pull-left" id="nino-navbar-collapse">




						</div>




					</div>


				</div><!-- /.container-fluid -->
			</nav>


		</div>
	</header><!--/#header-->
<!-- ========================================================================================= -->


	<section id="nino-story">
		<div class="container">
			<h2 class="nino-sectionHeading">
				<span class="nino-subHeading">Tutoria Login</span>
				For Student
			</h2>

      <a href="{% url 'index' %}" class="nino-btn1 w3-right"> Previous </a>
      <br><br>
  <h1> Please enter username and password </h1> <br>
  <form action="{% url 'main:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input class="searchForm" type="text" name="username" placeholder="Enter Username">
      <label for="password">Password:</label>

      <input class="searchForm" type="password" name="password" placeholder="Enter Password">&nbsp&nbsp
      <input type="submit" name="" class="nino-btn1" value="Login" >
      <p>
       <a href="{% url 'password_reset' %}"><br>
           Forgot your password?
       </a>
   </p>
    </form>

</div>
</section><!--/#nino-story-->


<footer id="footer" class="footer">
  <div class="container text-center">
      <div class="row">
          <div class="col-md-6 col-md-offset-3 col-sm-12 col-xs-12">
              <div class="main-footer">
                  <p>Made with <i class="fa fa-heart"></i> by <b>The Binary Baboons</b> 2017</p>

              </div>
          </div>
      </div>
  </div>

</footer>
<!-- Scroll to top
================================================== -->
<a href="#" id="nino-scrollToTop">Go to Top</a>

<!-- javascript -->
<script type="text/javascript" src="js/jquery.min.js"></script>
<script type="text/javascript" src="js/isotope.pkgd.min.js"></script>
<script type="text/javascript" src="js/jquery.prettyPhoto.js"></script>
<script type="text/javascript" src="js/bootstrap.min.js"></script>
<script type="text/javascript" src="js/jquery.hoverdir.js"></script>
<script type="text/javascript" src="js/modernizr.custom.97074.js"></script>
<script type="text/javascript" src="js/jquery.mCustomScrollbar.concat.min.js"></script>
<script type="text/javascript" src="js/unslider-min.js"></script>
<script type="text/javascript" src="js/template.js"></script>

</body>
</html>

templates/main/registration.html
   <!DOCTYPE html>
   {% load staticfiles %}
   <html lang="en">
   <head>
   	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
   	<meta name="viewport" content="width=device-width, initial-scale=1.0">
   	<meta name="description" content="">

     <meta charset="utf-8">
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
     <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
     <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
     <link rel="stylesheet" type="text/css" href="{% static 'css/materialdesignicons.min.css' %}" />
     <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}" />
     <link rel="stylesheet" type="text/css" href="{% static 'css/prettyPhoto.css' %}" />
     <link rel="stylesheet" type="text/css" href="{% static 'css/unslider.css' %}" />
     <link rel="stylesheet" type="text/css" href="{% static 'css/template.css' %}" />
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
   <title> Tutoria </title>

   </head>

   <body data-target="#nino-navbar" data-spy="scroll">

   	<!-- Header
       ================================================== -->
   	<header id="nino-header">
   		<div id="nino-headerInner">
   			<nav id="nino-navbar" class="navbar navbar-default" role="navigation">
   				<div class="container">

   					<!-- Brand and toggle get grouped for better mobile display -->
   					<div class="navbar-header">
   						<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nino-navbar-collapse">
   							<span class="sr-only">Toggle navigation</span>
   							<span class="icon-bar"></span>
   							<span class="icon-bar"></span>
   							<span class="icon-bar"></span>
   						</button>
   						<a class="navbar-brand" href="{% url 'index' %}">Tutoria</a>
   					</div>

   					<!-- Collect the nav links, forms, and other content for toggling -->


   					<div class="nino-menuItem pull-right">
   						<div class="collapse navbar-collapse pull-left" id="nino-navbar-collapse">


   						</div>




   					</div>


   				</div><!-- /.container-fluid -->
   			</nav>


   		</div>
   	</header><!--/#header-->
   <!-- ========================================================================================= -->


   	<section id="nino-story">
   		<div class="container">
   			<h2 class="nino-sectionHeading">
   				<span class="nino-subHeading">Tutoria Registration</span>
   				For User
   			</h2>



            {% if registered %}
            <!-- <p> {{user.id}} </p> -->
           <h1> Thank you for registering! </h1>
             <!-- <li><a href="{% url 'main:user_login' %}">LOGIN HERE</a></li> -->
              <a href="{% url 'main:studentreg' %}?value1={{user.username}}"><button class="w3-button w3-round-large  w3-ripple nino-clr">Register as Student</button></a>&nbsp&nbsp
            <a href="{% url 'main:tutorreg' %}?value1={{user.username}}"><button class="w3-button w3-round-large  w3-ripple nino-clr">Register as Tutor or Both</button></a>&nbsp&nbsp

           {% else %}
           <a href="{% url 'index' %}" class="nino-btn1 w3-right"> Previous </a>
           <br><br>

           <h2>Register Here! </h1>
           <h3> Fill out this form:</h3>
           <form enctype="multipart/form-data" method="post" >
               {% csrf_token %}
               {{ user_form.as_p }}
               <!-- {{ Student_form.as_p }} -->
               <input type="submit" name=" " value="Register"  class="nino-btn1">
          </form>
          {% endif %}




   </div>
   </section><!--/#nino-story-->


   <footer id="footer" class="footer">
     <div class="container text-center">
         <div class="row">
             <div class="col-md-6 col-md-offset-3 col-sm-12 col-xs-12">
                 <div class="main-footer">
                     <p>Made with <i class="fa fa-heart"></i> by <b>The Binary Baboons</b> 2017</p>

                 </div>
             </div>
         </div>
     </div>

   </footer>
   <!-- Scroll to top
   ================================================== -->
   <a href="#" id="nino-scrollToTop">Go to Top</a>

   <!-- javascript -->
   <script type="text/javascript" src="js/jquery.min.js"></script>
   <script type="text/javascript" src="js/isotope.pkgd.min.js"></script>
   <script type="text/javascript" src="js/jquery.prettyPhoto.js"></script>
   <script type="text/javascript" src="js/bootstrap.min.js"></script>
   <script type="text/javascript" src="js/jquery.hoverdir.js"></script>
   <script type="text/javascript" src="js/modernizr.custom.97074.js"></script>
   <script type="text/javascript" src="js/jquery.mCustomScrollbar.concat.min.js"></script>
   <script type="text/javascript" src="js/unslider-min.js"></script>
   <script type="text/javascript" src="js/template.js"></script>

   </body>
   </html>

templates/main/studentAndTutorReg.html
{% extends 'main/base.html' %}
{% block body_block %}
<div class="jumbotron">
  {% if registered %}
  <h1> Thank you for registering! </h1>
  <!-- <h3> Fill out this form:</h3> -->
  {% else %}
  <form enctype="multipart/form-data" method="post" >
      {% csrf_token %}
      <!-- {{ user_form.as_p }} -->
      {{ Tutor_form.as_p }}

      <input type="submit" name=" " value="Register">
 </form>
 {% endif %}

 </div>
   {% endblock %}