The_Tutoria_Project/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from main import views
from django.contrib import admin
from django.conf import settings
from django.contrib.auth.views import (
   password_reset,
   password_reset_done,
   password_reset_confirm,
   password_reset_complete
)

from The_Tutoria_Project.admin import courseadmin


urlpatterns = [

    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^main/', include('main.urls')),
    url(r'^', include('django.contrib.auth.urls')),


    # url(r'^admin/', admin.site.urls),
    # url(r'^account/', include('django.contrib.auth.urls')),
    # the new password reset URLs
    # url(r'^accounts/password/reset/$',
    #     password_reset,
    #     {'template_name':
    #     'registration/password_reset_form.html'},
    #     name="password_reset"),
    # url(r'^accounts/password/reset/done/$',
    #     password_reset_done,
    #     {'template_name':
    #     'registration/password_reset_done.html'},
    #     name="password_reset_done"),
    # url(r'^accounts/password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
    #     password_reset_confirm,
    #     {'template_name':
    #     'registration/password_reset_confirm.html'},
    #     name="password_reset_confirm"),
    # url(r'^accounts/password/done/$',
    #     password_reset_complete,
    #     {'template_name':
    #     'registration/password_reset_complete.html'},
    #     name="password_reset_complete"),
    # url(r'^accounts/',
    #     include('registration.backends.simple.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^courseadmin/', courseadmin.urls),


    #url(r'^accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.conf.urls import url

from django.views.generic.detail import DetailView
from django.conf.urls.static import static
from main import views
from django.conf import settings
from django.conf.urls import include, url
# from main.admin import my_new_admin
from django.contrib import admin
from django.contrib.auth.views import (
   password_reset,
   password_reset_done,
   password_reset_confirm,
   password_reset_complete
)

app_name = 'main'

urlpatterns = [
    url(r'^$', views.IndexView.as_view()),
    url(r'^home/$', views.homePage, name='home-page'),
    url(r'^search/$', views.search, name='search'),
    url(r'^reset-password/$',password_reset, name = 'password_reset'),
    url(r'^reset-password/done/$',password_reset_done, name = 'password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',password_reset_confirm, name = 'password_reset_confirm'),
    url(r'^reset-password/complete/$',password_reset_complete, name = 'password_reset_complete'),
    url(r'^register/$', views.register, name='register'),
    url(r'^studentreg/$', views.studentRegistration, name='studentreg'),
    url(r'^tutorreg/$', views.register2, name='tutorreg'),
    url(r'^change_password/$', views.change_password, name='change_password'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^tutorWallet/$', views.tutorWallet, name='tutorWallet'),
    url(r'^studentWallet/$', views.studentWallet, name='studentWallet'),
    url(r'^myTutorsWallet/$', views.myTutorsWallet, name='myTutorsWallet'),
    url(r'^tutorSchedule/$', views.tutorSchedule, name='tutorSchedule'),
    url(r'^blockSuccess/$', views.blockSuccess, name='blockSuccess'),
    url(r'^user_login/$', views.user_login, name='user_login'),
    url(r'^tutor_login/$', views.user_login1, name='tutor_login'),
    url(r'^tutorhome/$', views.tutorHome, name='tutor_home'),
    url(r'^session/$', views.bookSession, name='session'),
    url(r'^confirmedBooking/$', views.confirmedBooking, name='confirmedBooking'),
    url(r'^mySessions/$', views.mySessions, name='mySessions'),
    url(r'^tutors$', views.TutorListView.as_view(), name='tutor-list'),
    url(r'^tutors/(?P<pk>\d+)$', views.TutorDetailView, name='tutor-detail'),
    url(r'^tutors/viewprofile/', views.TutorViewProfile, name='tutor-viewprofile'),
    url(r'^myTutors$', views.myTutorsHome, name='myTutors'),
    url(r'^tutors/update/(?P<pk>\d+)$', views.TutorUpdateView.as_view(), name='tutor-update'),
    url(r'^reviews$', views.review, name='review-list'),
    url(r'^reviews/(?P<pk>\d+)$', views.reviewForm, name='review-form'),
    url(r'^tutorMySessions$', views.tutorMySessions, name='tutorMySessions')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
  	<link rel="stylesheet" type="text/css" href="{% static 'css/materialdesignicons.min.css' %}" />
  	<link rel="stylesheet" type="text/css" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}" />
  	<link rel="stylesheet" type="text/css" href="{% static 'css/prettyPhoto.css' %}" />
  	<link rel="stylesheet" type="text/css" href="{% static 'css/unslider.css' %}" />
  	<link rel="stylesheet" type="text/css" href="{% static 'css/template.css' %}" />
  	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <title>Tutoria</title>
</head>
    <body data-target="#nino-navbar" data-spy="scroll">
    <nav class="navbar navbar-default navbar-static-top">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'main:tutor-list' %}">Tutors</a></li>
          <li><a class="navbar-brand" href="{% url 'admin:index' %}">Admin</a></li>

          {% if user.is_authenticated %}
                 <li><a class='navbar-link' href="{% url 'logout' %}">Logout</a></li>
          {% else %}
                  <li><a class="navbar-link" href="{% url 'main:user_login' %}">Login</a></li>
          {% endif %}

          <li><a class="navbar-link" href="{% url 'main:register' %}">Register</a></li>
          <li><a class="navbar-link" href="{% url 'main:mySessions' %}">My Sessions</a></li>

        </ul>
    </nav>



    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>

  </body>

templates/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">

	<title>Tutoria</title>
	<!-- css -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/materialdesignicons.min.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/prettyPhoto.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/unslider.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/template.css' %}" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>

<body data-target="#nino-navbar" data-spy="scroll">

	<!-- Header
    ================================================== -->
	<header id="nino-header">
		<div id="nino-headerInner">
			<nav id="nino-navbar" class="navbar navbar-default" role="navigation">
				<div class="container">

					<!-- Brand and toggle get grouped for better mobile display -->
					<div class="navbar-header">
						<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nino-navbar-collapse">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<a class="navbar-brand">Tutoria</a>
					</div>

					<!-- Collect the nav links, forms, and other content for toggling -->


					<div class="nino-menuItem pull-right">
						<div class="collapse navbar-collapse pull-left" id="nino-navbar-collapse">

							<!--
							<ul class="nav navbar-nav">
								<li class="active"><a href="#nino-header">Home <span class="sr-only">(current)</span></a></li>
								<li><a href="#nino-story">About</a></li>
								<li><a href="#nino-services">Service</a></li>
								<li><a href="#nino-ourTeam">Our Team</a></li>
								<li><a href="#nino-portfolio">Work</a></li>
								<li><a href="#nino-latestBlog">Blog</a></li>
							</ul>
						</div>
						<ul class="nino-iconsGroup nav navbar-nav">
							<li><a href="#"><i class="mdi mdi-cart-outline nino-icon"></i></a></li>
							<li><a href="#" class="nino-search"><i class="mdi mdi-magnify nino-icon"></i></a></li>
						</ul>
					-->



					</div>


				</div><!-- /.container-fluid -->
			</nav>

			<section id="nino-slider" class="carousel slide container" data-ride="carousel">

				<!-- Wrapper for slides -->
				<div class="carousel-inner" role="listbox">
					<div class="item active">
						<h2 class="nino-sectionHeading">
							<span class="nino-subHeading">Welcome to</span>
							Tutoria
						</h2>
						<a class="nino-btn">Choose a slider option from below to begin</a>
					</div>


					<div class="item">
						<h2 class="nino-sectionHeading">
							<span class="nino-subHeading">Sign in as Student</span>

						</h2>
						<a href="main/user_login" class="nino-btn">Sign in as Student</a>
					</div>


					<div class="item">
						<h2 class="nino-sectionHeading">
							<span class="nino-subHeading">Sign in as Tutor</span>
						</h2>
						<a href="main/tutor_login" class="nino-btn">Sign in as Tutor</a>
					</div>


					<div class="item">
						<h2 class="nino-sectionHeading">
							<span class="nino-subHeading">Sign up for</span>
							Tutoria
						</h2>
						<a href="main/register" class="nino-btn">Sign up</a>
					</div>
				</div>

				<!-- Indicators -->
				<ol class="carousel-indicators clearfix">
					<li data-target="#nino-slider" data-slide-to="0" class="active">
						<div class="inner">
							<span class="number">01</span> Welcome
						</div>
					</li>
					<li data-target="#nino-slider" data-slide-to="1">
						<div class="inner">
							<span class="number">02</span> Sign in as Student
						</div>
					</li>
					<li data-target="#nino-slider" data-slide-to="2">
						<div class="inner">
							<span class="number">03</span> <span>Sign in as Tutors</span>
						</div>
					</li>
					<li data-target="#nino-slider" data-slide-to="3">
						<div class="inner">
							<span class="number">04</span> Register
						</div>
					</li>
				</ol>
			</section>
		</div>
	</header><!--/#header-->

	<!-- Story About Us
    ================================================== -->
	<section id="nino-story">
		<div class="container">
			<h2 class="nino-sectionHeading">
				<span class="nino-subHeading">An introduction</span>
				What is Tutoria
			</h2>
			<p class="nino-sectionDesc"> Tutoria is a project that brings Students and Tutors together! </p>
			<div class="sectionContent">
				<div class="row nino-hoverEffect">
					<div class="col-md-3 col-sm-3">
						<div class="item">
							<a class="overlay">
								<span class="content">
									Sidhant Gupta
								</span>
								<img src="{% static 'images/story/img-3.jpg' %}" alt="" class='a'>
							</a>
						</div>

					</div>
					<div class="col-md-3 col-sm-3">
						<div class="item">
							<a class="overlay">
								<span class="content">
									Sagar Gupta
								</span>
								<img src="{% static 'images/story/img-7.jpg' %}" alt="">
							</a>
						</div>
					</div>
					<div class="col-md-3 col-sm-3">
						<div class="item">
							<a class="overlay">
								<span class="content">
									Rachaika Verma
								</span>
								<img src="{% static 'images/story/img-4.jpg' %}" alt="">
							</a>
						</div>
					</div>
					<div class="col-md-3 col-sm-3">
						<div class="item">
							<a class="overlay">
								<span class="content">
									Varun Vamsi
								</span>
								<img src="{% static 'images/story/img-2.jpg' %}" alt="">
							</a>
						</div>
					</div>
				</div>
			</div>
		</div>
    <div class="margin-top-60">
	</section><!--/#nino-story-->
	<footer id="footer" class="footer">
			<div class="container text-center">
					<div class="row">
							<div class="col-md-6 col-md-offset-3 col-sm-12 col-xs-12">
									<div class="main-footer">
											<p>Made with <i class="fa fa-heart"></i> by <b>The Binary Baboons</b> 2017</p>
                      <a href="/courseadmin">Login as Admin</a>
                      <a  href="/main/myTutors">Login as MyTutors</a>

									</div>
							</div>
					</div>
			</div>

	</footer>
    <!-- Scroll to top
    ================================================== -->
	<a href="#" id="nino-scrollToTop">Go to Top</a>

	<!-- javascript -->
	<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/isotope.pkgd.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery.prettyPhoto.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery.hoverdir.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/modernizr.custom.97074.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/unslider-min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/template.js' %}"></script>

</body>
</html>